
import { createResourceHooks } from './factories/createResourceHooks';
import * as medicalCategoriesService from 'services/api/medical-categories.service';

/**
 * Standardized hooks for Medical Categories
 * Generated by ResourceHookFactory (React Query Supported)
 */
const {
  useList: useMedicalCategoriesList,
  useDetails: useMedicalCategoryDetails,
  useAll: useAllMedicalCategories,
  useCreate: useCreateMedicalCategory,
  useUpdate: useUpdateMedicalCategory,
  useDelete: useDeleteMedicalCategory
} = createResourceHooks({
  queryKey: 'medical-categories',
  service: medicalCategoriesService,
  methods: {
    list: 'getMedicalCategories',
    details: 'getMedicalCategoryById',
    all: 'getAllMedicalCategories',
    create: 'createMedicalCategory',   // Assumed name, will verify
    update: 'updateMedicalCategory',   // Assumed name
    delete: 'deleteMedicalCategory'    // Assumed name
  }
});

export {
  useMedicalCategoriesList,
  useMedicalCategoryDetails,
  useAllMedicalCategories,
  useCreateMedicalCategory,
  useUpdateMedicalCategory,
  useDeleteMedicalCategory
};
