-- ═══════════════════════════════════════════════════════════════════════════
-- V32: Create System Settings Table
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS system_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    setting_key VARCHAR(100) NOT NULL UNIQUE,
    setting_value TEXT NOT NULL,
    value_type VARCHAR(20) NOT NULL DEFAULT 'STRING',
    description TEXT,
    category VARCHAR(50),
    
    is_editable BOOLEAN NOT NULL DEFAULT TRUE,
    default_value TEXT,
    validation_rules TEXT,
    
    active BOOLEAN NOT NULL DEFAULT TRUE,
    
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(100)
);

-- Add unique constraint on setting_key (redundant with UNIQUE above, but good for clarity based on Entity)
-- ALTER TABLE system_settings ADD CONSTRAINT uk_setting_key UNIQUE (setting_key);
