package com.waad.tba.services.pdf.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Map;

/**
 * Metadata for PDF Report Generation
 * 
 * ARCHITECTURAL RULE:
 * This DTO contains all metadata needed for PDF generation.
 * Never pass JPA Entities directly to PDF services.
 * 
 * @since 2026-01-06
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PdfReportMetadata {
    
    /**
     * Report title (Arabic + English)
     */
    private String titleAr;
    private String titleEn;
    
    /**
     * Report type (MEMBER, PROVIDER, CONTRACT, CLAIM, etc.)
     */
    private ReportType reportType;
    
    /**
     * Report orientation
     */
    private PageOrientation orientation;
    
    /**
     * Generation timestamp
     */
    private LocalDateTime generatedAt;
    
    /**
     * Tracking ID for audit trail
     */
    private String trackingId;
    
    /**
     * System/Company logo path
     */
    private String logoPath;
    
    /**
     * Generated by user
     */
    private String generatedBy;
    
    /**
     * Custom parameters (flexible for different reports)
     */
    private Map<String, Object> customParams;
    
    /**
     * Show watermark (e.g., "DRAFT", "CONFIDENTIAL")
     */
    private String watermark;
    
    public enum ReportType {
        MEMBER,
        PROVIDER,
        CONTRACT,
        PRICING,
        CLAIM,
        PREAUTHORIZATION,
        BENEFIT_POLICY,
        DASHBOARD,
        FINANCIAL,
        AUDIT
    }
    
    public enum PageOrientation {
        PORTRAIT,
        LANDSCAPE
    }
}
