package com.waad.tba.modules.settlement.api.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * ╔═══════════════════════════════════════════════════════════════════════════════╗
 * ║              CREATE SETTLEMENT BATCH REQUEST - API CONTRACT v1                ║
 * ╚═══════════════════════════════════════════════════════════════════════════════╝
 * 
 * PUBLIC API CONTRACT for creating settlement batches.
 * 
 * FINANCIAL SAFETY RULES:
 * ✓ Frontend NEVER sends monetary values
 * ✓ Only claim IDs are accepted
 * ✓ Backend calculates all amounts from database
 * ✓ Immutable after creation (use separate add/remove endpoints)
 * 
 * @since API v1
 * @see SETTLEMENT_API_CONTRACT.md
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Request to create a new settlement batch")
public class CreateSettlementBatchRequest {

    /**
     * Provider ID for which to create the settlement batch.
     * REQUIRED - Must exist in database.
     */
    @NotNull(message = "Provider ID is required")
    @Schema(
        description = "Provider ID for the settlement batch",
        example = "123",
        required = true
    )
    private Long providerId;
    
    /**
     * Optional description/notes for the batch.
     * Maximum 500 characters.
     */
    @Size(max = 500, message = "Description cannot exceed 500 characters")
    @Schema(
        description = "Optional description for the batch",
        example = "January 2026 settlements for Al-Shifa Hospital",
        maxLength = 500
    )
    private String description;
    
    /**
     * Optional list of claim IDs to add immediately to the batch.
     * 
     * IMPORTANT VALIDATIONS (Backend enforced):
     * - Claims must be in APPROVED status
     * - Claims must belong to the specified provider
     * - Claims must not be in any other batch
     * - Claims must have valid net payable amounts > 0
     * 
     * If empty/null, creates an empty DRAFT batch.
     */
    @Schema(
        description = "Optional list of claim IDs to add to the batch immediately",
        example = "[456, 457, 458]"
    )
    private List<Long> claimIds;
    
    // ═══════════════════════════════════════════════════════════════════════════
    // EXPLICITLY FORBIDDEN FIELDS (compile-time prevention)
    // ═══════════════════════════════════════════════════════════════════════════
    
    // ❌ NO totalAmount - calculated by backend
    // ❌ NO netAmount - calculated by backend  
    // ❌ NO grossAmount - calculated by backend
    // ❌ NO deductions - calculated by backend
    // ❌ NO status - always DRAFT on creation
    // ❌ NO batchNumber - generated by backend
    // ❌ NO createdBy - extracted from JWT
    // ❌ NO createdAt - set by backend
}
