package com.waad.tba.modules.claim.api.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * ════════════════════════════════════════════════════════════════════════════
 * API v1 Contract: Settle Claim Request (DEPRECATED)
 * ════════════════════════════════════════════════════════════════════════════
 * 
 * ⚠️⚠️⚠️ DEPRECATED AS OF 2026-02-01 ⚠️⚠️⚠️
 * 
 * Per-claim settlement is DISABLED. All settlements must now go through
 * the Settlement Batches system.
 * 
 * REPLACEMENT WORKFLOW:
 * 1. POST /api/v1/settlement-batches - Create batch
 * 2. POST /api/v1/settlement-batches/{id}/add-claims - Add claims to batch
 * 3. POST /api/v1/settlement-batches/{id}/confirm - Confirm batch (locks financials)
 * 4. POST /api/v1/settlement-batches/{id}/pay - Execute payment
 * 
 * FINANCIAL SAFETY:
 * The Settlement Batches API is CONTRACT-PROTECTED and BACKEND-AUTHORITATIVE.
 * Payment amounts are calculated from approved claims, not from frontend input.
 * 
 * This contract is kept for backwards compatibility but will throw an error
 * if used.
 * 
 * @since API v1.0
 * @version 2026-02-01
 * @deprecated Use Settlement Batches API instead
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Deprecated
public class SettleClaimRequest {
    
    /**
     * Payment reference number from finance system.
     * 
     * @deprecated Use Settlement Batches API
     */
    @NotBlank(message = "Payment reference is required")
    @Size(max = 100, message = "Payment reference must not exceed 100 characters")
    @Deprecated
    private String paymentReference;
    
    /**
     * Optional settlement notes.
     * 
     * @deprecated Use Settlement Batches API
     */
    @Size(max = 1000, message = "Notes must not exceed 1000 characters")
    @Deprecated
    private String notes;
    
    // ═══════════════════════════════════════════════════════════════════════════
    // ⛔ FORBIDDEN FIELDS - FINANCIAL SAFETY
    // ═══════════════════════════════════════════════════════════════════════════
    // Even in the old (deprecated) system, these fields were NEVER allowed:
    // 
    // ❌ settlementAmount - Must match approved amount (backend validates)
    // ❌ paymentDate - Backend sets to current date
    // ❌ bankReference - Generated by payment gateway
    // 
    // The Settlement Batches API enforces these rules with API v1 contracts.
    // ═══════════════════════════════════════════════════════════════════════════
}
